parameters:
#    warsztat.example.class: ZPI\WarsztatBundle\Example

services:
#    warsztat.example:
#        class: %warsztat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
